### ISSUE TITLE
Help with setting up this project locally

### ISSUE THREAD

**Issue by alotia** [geekymon2/carmarketplace-imgstore-svc#1]
Hi,

I cloned most of the repos, but I cannot seem to build the top-level app or any of the submodules.

Can you please provide some instructions on how to set up your 'carmarketplace' project locally, including setting the folder structure for the different repos. For example, are these individual repos clone under the 'carmarketplace' application repo, or at the peer level?

Thanks!

**Comment by codemanxdev** [comment]
Hi, All repos need to be cloned seperately, they are independent projects that can run separately. What i the error you get when you build the project?

**Comment by geekymon2** [comment]
Hi, All repos need to be cloned seperately, they are independent projects that can run separately. What i the error you get when you build the project?

**Comment by codemanxdev** [comment]
Hi @alotia , I found out the maven build issue was related to the build order in which the projects are being build, I have added instructions on the README.md of the carmarketplace repo, Please go through the build section to see the information. Let me know if you are still having issues.

**Comment by alotia** [comment]
@geekymon2 Thank you for updating the README. Works good now!

**Comment by alotia** [comment]
Works well now. Thanks!
